package com.madrid.parking.android.model;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 9/14/2015 2:13:24 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;

import java.util.Hashtable;

import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class featureType implements KvmSerializable {

    public String description;
    public String name;
    public String nameCode;
    public String nameField;
    public String nameFieldTranslated;
    public String urlIcon;

    public featureType() {
    }

    public featureType(SoapObject soapObject) {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("description")) {
            Object obj = soapObject.getProperty("description");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                description = j.toString();
            } else if (obj != null && obj instanceof String) {
                description = (String) obj;
            }
        }
        if (soapObject.hasProperty("name")) {
            Object obj = soapObject.getProperty("name");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                name = j.toString();
            } else if (obj != null && obj instanceof String) {
                name = (String) obj;
            }
        }
        if (soapObject.hasProperty("nameCode")) {
            Object obj = soapObject.getProperty("nameCode");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                nameCode = j.toString();
            } else if (obj != null && obj instanceof String) {
                nameCode = (String) obj;
            }
        }
        if (soapObject.hasProperty("nameField")) {
            Object obj = soapObject.getProperty("nameField");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                nameField = j.toString();
            } else if (obj != null && obj instanceof String) {
                nameField = (String) obj;
            }
        }
        if (soapObject.hasProperty("nameFieldTranslated")) {
            Object obj = soapObject.getProperty("nameFieldTranslated");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                nameFieldTranslated = j.toString();
            } else if (obj != null && obj instanceof String) {
                nameFieldTranslated = (String) obj;
            }
        }
        if (soapObject.hasProperty("urlIcon")) {
            Object obj = soapObject.getProperty("urlIcon");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                urlIcon = j.toString();
            } else if (obj != null && obj instanceof String) {
                urlIcon = (String) obj;
            }
        }
    }

    @Override
    public Object getProperty(int arg0) {
        switch (arg0) {
            case 0:
                return description;
            case 1:
                return name;
            case 2:
                return nameCode;
            case 3:
                return nameField;
            case 4:
                return nameFieldTranslated;
            case 5:
                return urlIcon;
        }
        return null;
    }

    @Override
    public int getPropertyCount() {
        return 6;
    }

    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch (index) {
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "description";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "name";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "nameCode";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "nameField";
                break;
            case 4:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "nameFieldTranslated";
                break;
            case 5:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "urlIcon";
                break;
        }
    }


    public String getInnerText() {
        return null;
    }


    public void setInnerText(String s) {
    }


    @Override
    public void setProperty(int arg0, Object arg1) {
    }

}
