package com.madrid.parking.android.model;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 9/14/2015 2:13:24 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;

import java.util.Hashtable;

import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class nameFieldParking implements KvmSerializable {

    public codes codes;
    public String nameField;

    public nameFieldParking() {
    }

    public nameFieldParking(SoapObject soapObject) {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("codes")) {
            SoapObject j = (SoapObject) soapObject.getProperty("codes");
            codes = new codes(j);

        }
        if (soapObject.hasProperty("nameField")) {
            Object obj = soapObject.getProperty("nameField");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                nameField = j.toString();
            } else if (obj != null && obj instanceof String) {
                nameField = (String) obj;
            }
        }
    }

    @Override
    public Object getProperty(int arg0) {
        switch (arg0) {
            case 0:
                return codes;
            case 1:
                return nameField;
        }
        return null;
    }

    @Override
    public int getPropertyCount() {
        return 2;
    }

    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch (index) {
            case 0:
                info.type = codes.class;
                info.name = "codes";
                info.setNamespace("http://schemas.datacontract.org/2004/07/InfoParking");
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "nameField";
                info.setNamespace("http://schemas.datacontract.org/2004/07/InfoParking");
                break;
        }
    }


    public String getInnerText() {
        return null;
    }


    public void setInnerText(String s) {
    }


    @Override
    public void setProperty(int arg0, Object arg1) {
    }

}
