package com.madrid.parking.android.model;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 9/14/2015 2:13:24 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;

import java.util.Hashtable;

import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class parkingDetails implements KvmSerializable {

    public String family;
    public String familyCode;
    public generalData general;
    public int id;
    public boolean idSpecified;
    public Vectoraccess lstAccess;
    public Vectorfeature lstFeatures;
    public Vectoroccupation lstOccupation;
    public Vectorrates lstRates;
    public String name;
    public String schedule;

    public parkingDetails() {
    }

    public parkingDetails(SoapObject soapObject) {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("family")) {
            Object obj = soapObject.getProperty("family");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                family = j.toString();
            } else if (obj != null && obj instanceof String) {
                family = (String) obj;
            }
        }
        if (soapObject.hasProperty("familyCode")) {
            Object obj = soapObject.getProperty("familyCode");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                familyCode = j.toString();
            } else if (obj != null && obj instanceof String) {
                familyCode = (String) obj;
            }
        }
        if (soapObject.hasProperty("general")) {
            SoapObject j = (SoapObject) soapObject.getProperty("general");
            general = new generalData(j);

        }
        if (soapObject.hasProperty("id")) {
            Object obj = soapObject.getProperty("id");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                id = Integer.parseInt(j.toString());
            } else if (obj != null && obj instanceof Number) {
                id = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("idSpecified")) {
            Object obj = soapObject.getProperty("idSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                idSpecified = Boolean.parseBoolean(j.toString());
            } else if (obj != null && obj instanceof Boolean) {
                idSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("lstAccess")) {
            SoapObject j = (SoapObject) soapObject.getProperty("lstAccess");
            lstAccess = new Vectoraccess(j);
        }
        if (soapObject.hasProperty("lstFeatures")) {
            SoapObject j = (SoapObject) soapObject.getProperty("lstFeatures");
            lstFeatures = new Vectorfeature(j);
        }
        if (soapObject.hasProperty("lstOccupation")) {
            SoapObject j = (SoapObject) soapObject.getProperty("lstOccupation");
            lstOccupation = new Vectoroccupation(j);
        }
        if (soapObject.hasProperty("lstRates")) {
            SoapObject j = (SoapObject) soapObject.getProperty("lstRates");
            lstRates = new Vectorrates(j);
        }
        if (soapObject.hasProperty("name")) {
            Object obj = soapObject.getProperty("name");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                name = j.toString();
            } else if (obj != null && obj instanceof String) {
                name = (String) obj;
            }
        }
        if (soapObject.hasProperty("schedule")) {
            Object obj = soapObject.getProperty("schedule");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                schedule = j.toString();
            } else if (obj != null && obj instanceof String) {
                schedule = (String) obj;
            }
        }
    }

    @Override
    public Object getProperty(int arg0) {
        switch (arg0) {
            case 0:
                return family;
            case 1:
                return familyCode;
            case 2:
                return general;
            case 3:
                return id;
            case 4:
                return idSpecified;
            case 5:
                return lstAccess;
            case 6:
                return lstFeatures;
            case 7:
                return lstOccupation;
            case 8:
                return lstRates;
            case 9:
                return name;
            case 10:
                return schedule;
        }
        return null;
    }

    @Override
    public int getPropertyCount() {
        return 11;
    }

    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch (index) {
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "family";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "familyCode";
                break;
            case 2:
                info.type = generalData.class;
                info.name = "general";
                break;
            case 3:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "id";
                break;
            case 4:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "idSpecified";
                break;
            case 5:
                info.type = PropertyInfo.VECTOR_CLASS;
                info.name = "lstAccess";
                break;
            case 6:
                info.type = PropertyInfo.VECTOR_CLASS;
                info.name = "lstFeatures";
                break;
            case 7:
                info.type = PropertyInfo.VECTOR_CLASS;
                info.name = "lstOccupation";
                break;
            case 8:
                info.type = PropertyInfo.VECTOR_CLASS;
                info.name = "lstRates";
                break;
            case 9:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "name";
                break;
            case 10:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "schedule";
                break;
        }
    }


    public String getInnerText() {
        return null;
    }


    public void setInnerText(String s) {
    }


    @Override
    public void setProperty(int arg0, Object arg1) {
    }

}
