package com.madrid.parking.android.model;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 9/14/2015 2:13:24 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;

import java.util.Hashtable;

import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class poiDetailGeneral implements KvmSerializable {

    public String address;
    public String administrativeArea;
    public String areaCode;
    public String category;
    public String categoryCode;
    public String country;
    public String email;
    public String fax;
    public String icon;
    public String latitude;
    public String longitude;
    public String state;
    public String telephone;
    public String town;
    public String type;
    public String typeCode;

    public poiDetailGeneral() {
    }

    public poiDetailGeneral(SoapObject soapObject) {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("address")) {
            Object obj = soapObject.getProperty("address");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                address = j.toString();
            } else if (obj != null && obj instanceof String) {
                address = (String) obj;
            }
        }
        if (soapObject.hasProperty("administrativeArea")) {
            Object obj = soapObject.getProperty("administrativeArea");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                administrativeArea = j.toString();
            } else if (obj != null && obj instanceof String) {
                administrativeArea = (String) obj;
            }
        }
        if (soapObject.hasProperty("areaCode")) {
            Object obj = soapObject.getProperty("areaCode");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                areaCode = j.toString();
            } else if (obj != null && obj instanceof String) {
                areaCode = (String) obj;
            }
        }
        if (soapObject.hasProperty("category")) {
            Object obj = soapObject.getProperty("category");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                category = j.toString();
            } else if (obj != null && obj instanceof String) {
                category = (String) obj;
            }
        }
        if (soapObject.hasProperty("categoryCode")) {
            Object obj = soapObject.getProperty("categoryCode");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                categoryCode = j.toString();
            } else if (obj != null && obj instanceof String) {
                categoryCode = (String) obj;
            }
        }
        if (soapObject.hasProperty("country")) {
            Object obj = soapObject.getProperty("country");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                country = j.toString();
            } else if (obj != null && obj instanceof String) {
                country = (String) obj;
            }
        }
        if (soapObject.hasProperty("email")) {
            Object obj = soapObject.getProperty("email");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                email = j.toString();
            } else if (obj != null && obj instanceof String) {
                email = (String) obj;
            }
        }
        if (soapObject.hasProperty("fax")) {
            Object obj = soapObject.getProperty("fax");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                fax = j.toString();
            } else if (obj != null && obj instanceof String) {
                fax = (String) obj;
            }
        }
        if (soapObject.hasProperty("icon")) {
            Object obj = soapObject.getProperty("icon");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                icon = j.toString();
            } else if (obj != null && obj instanceof String) {
                icon = (String) obj;
            }
        }
        if (soapObject.hasProperty("latitude")) {
            Object obj = soapObject.getProperty("latitude");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                latitude = j.toString();
            } else if (obj != null && obj instanceof String) {
                latitude = (String) obj;
            }
        }
        if (soapObject.hasProperty("longitude")) {
            Object obj = soapObject.getProperty("longitude");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                longitude = j.toString();
            } else if (obj != null && obj instanceof String) {
                longitude = (String) obj;
            }
        }
        if (soapObject.hasProperty("state")) {
            Object obj = soapObject.getProperty("state");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                state = j.toString();
            } else if (obj != null && obj instanceof String) {
                state = (String) obj;
            }
        }
        if (soapObject.hasProperty("telephone")) {
            Object obj = soapObject.getProperty("telephone");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                telephone = j.toString();
            } else if (obj != null && obj instanceof String) {
                telephone = (String) obj;
            }
        }
        if (soapObject.hasProperty("town")) {
            Object obj = soapObject.getProperty("town");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                town = j.toString();
            } else if (obj != null && obj instanceof String) {
                town = (String) obj;
            }
        }
        if (soapObject.hasProperty("type")) {
            Object obj = soapObject.getProperty("type");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                type = j.toString();
            } else if (obj != null && obj instanceof String) {
                type = (String) obj;
            }
        }
        if (soapObject.hasProperty("typeCode")) {
            Object obj = soapObject.getProperty("typeCode");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                typeCode = j.toString();
            } else if (obj != null && obj instanceof String) {
                typeCode = (String) obj;
            }
        }
    }

    @Override
    public Object getProperty(int arg0) {
        switch (arg0) {
            case 0:
                return address;
            case 1:
                return administrativeArea;
            case 2:
                return areaCode;
            case 3:
                return category;
            case 4:
                return categoryCode;
            case 5:
                return country;
            case 6:
                return email;
            case 7:
                return fax;
            case 8:
                return icon;
            case 9:
                return latitude;
            case 10:
                return longitude;
            case 11:
                return state;
            case 12:
                return telephone;
            case 13:
                return town;
            case 14:
                return type;
            case 15:
                return typeCode;
        }
        return null;
    }

    @Override
    public int getPropertyCount() {
        return 16;
    }

    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch (index) {
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "address";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "administrativeArea";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "areaCode";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "category";
                break;
            case 4:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "categoryCode";
                break;
            case 5:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "country";
                break;
            case 6:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "email";
                break;
            case 7:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "fax";
                break;
            case 8:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "icon";
                break;
            case 9:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "latitude";
                break;
            case 10:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "longitude";
                break;
            case 11:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "state";
                break;
            case 12:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "telephone";
                break;
            case 13:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "town";
                break;
            case 14:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "type";
                break;
            case 15:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "typeCode";
                break;
        }
    }


    public String getInnerText() {
        return null;
    }


    public void setInnerText(String s) {
    }


    @Override
    public void setProperty(int arg0, Object arg1) {
    }

}
