package com.madrid.parking.android.model;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 9/14/2015 2:13:24 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;

import java.util.Hashtable;

import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class poiDetailInfo implements KvmSerializable {

    public String description;
    public String nameTranslated;
    public String schedule;
    public String servicesPayment;
    public String web;

    public poiDetailInfo() {
    }

    public poiDetailInfo(SoapObject soapObject) {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("description")) {
            Object obj = soapObject.getProperty("description");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                description = j.toString();
            } else if (obj != null && obj instanceof String) {
                description = (String) obj;
            }
        }
        if (soapObject.hasProperty("nameTranslated")) {
            Object obj = soapObject.getProperty("nameTranslated");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                nameTranslated = j.toString();
            } else if (obj != null && obj instanceof String) {
                nameTranslated = (String) obj;
            }
        }
        if (soapObject.hasProperty("schedule")) {
            Object obj = soapObject.getProperty("schedule");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                schedule = j.toString();
            } else if (obj != null && obj instanceof String) {
                schedule = (String) obj;
            }
        }
        if (soapObject.hasProperty("servicesPayment")) {
            Object obj = soapObject.getProperty("servicesPayment");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                servicesPayment = j.toString();
            } else if (obj != null && obj instanceof String) {
                servicesPayment = (String) obj;
            }
        }
        if (soapObject.hasProperty("web")) {
            Object obj = soapObject.getProperty("web");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                web = j.toString();
            } else if (obj != null && obj instanceof String) {
                web = (String) obj;
            }
        }
    }

    @Override
    public Object getProperty(int arg0) {
        switch (arg0) {
            case 0:
                return description;
            case 1:
                return nameTranslated;
            case 2:
                return schedule;
            case 3:
                return servicesPayment;
            case 4:
                return web;
        }
        return null;
    }

    @Override
    public int getPropertyCount() {
        return 5;
    }

    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch (index) {
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "description";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "nameTranslated";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "schedule";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "servicesPayment";
                break;
            case 4:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "web";
                break;
        }
    }


    public String getInnerText() {
        return null;
    }


    public void setInnerText(String s) {
    }


    @Override
    public void setProperty(int arg0, Object arg1) {
    }

}
