package com.madrid.parking.android.model;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 9/14/2015 2:13:24 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;

import java.util.Hashtable;

import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class PoisParking implements KvmSerializable {

    public String address;
    public String addressNumber;
    public String administrativeArea;
    public String areaCode;
    public String category;
    public String country;
    public String email;
    public String family;
    public String familyCode;
    public String fax;
    public int id;
    public boolean idSpecified;
    public String latitude;
    public String longitude;
    public String name;
    public String neutralIcon;
    public String nickName;
    public String state;
    public String telephone;
    public String town;
    public String type;

    public PoisParking() {
    }

    public PoisParking(SoapObject soapObject) {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("address")) {
            Object obj = soapObject.getProperty("address");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                address = j.toString();
            } else if (obj != null && obj instanceof String) {
                address = (String) obj;
            }
        }
        if (soapObject.hasProperty("addressNumber")) {
            Object obj = soapObject.getProperty("addressNumber");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                addressNumber = j.toString();
            } else if (obj != null && obj instanceof String) {
                addressNumber = (String) obj;
            }
        }
        if (soapObject.hasProperty("administrativeArea")) {
            Object obj = soapObject.getProperty("administrativeArea");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                administrativeArea = j.toString();
            } else if (obj != null && obj instanceof String) {
                administrativeArea = (String) obj;
            }
        }
        if (soapObject.hasProperty("areaCode")) {
            Object obj = soapObject.getProperty("areaCode");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                areaCode = j.toString();
            } else if (obj != null && obj instanceof String) {
                areaCode = (String) obj;
            }
        }
        if (soapObject.hasProperty("category")) {
            Object obj = soapObject.getProperty("category");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                category = j.toString();
            } else if (obj != null && obj instanceof String) {
                category = (String) obj;
            }
        }
        if (soapObject.hasProperty("country")) {
            Object obj = soapObject.getProperty("country");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                country = j.toString();
            } else if (obj != null && obj instanceof String) {
                country = (String) obj;
            }
        }
        if (soapObject.hasProperty("email")) {
            Object obj = soapObject.getProperty("email");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                email = j.toString();
            } else if (obj != null && obj instanceof String) {
                email = (String) obj;
            }
        }
        if (soapObject.hasProperty("family")) {
            Object obj = soapObject.getProperty("family");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                family = j.toString();
            } else if (obj != null && obj instanceof String) {
                family = (String) obj;
            }
        }
        if (soapObject.hasProperty("familyCode")) {
            Object obj = soapObject.getProperty("familyCode");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                familyCode = j.toString();
            } else if (obj != null && obj instanceof String) {
                familyCode = (String) obj;
            }
        }
        if (soapObject.hasProperty("fax")) {
            Object obj = soapObject.getProperty("fax");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                fax = j.toString();
            } else if (obj != null && obj instanceof String) {
                fax = (String) obj;
            }
        }
        if (soapObject.hasProperty("id")) {
            Object obj = soapObject.getProperty("id");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                id = Integer.parseInt(j.toString());
            } else if (obj != null && obj instanceof Number) {
                id = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("idSpecified")) {
            Object obj = soapObject.getProperty("idSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                idSpecified = Boolean.parseBoolean(j.toString());
            } else if (obj != null && obj instanceof Boolean) {
                idSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("latitude")) {
            Object obj = soapObject.getProperty("latitude");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                latitude = j.toString();
            } else if (obj != null && obj instanceof String) {
                latitude = (String) obj;
            }
        }
        if (soapObject.hasProperty("longitude")) {
            Object obj = soapObject.getProperty("longitude");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                longitude = j.toString();
            } else if (obj != null && obj instanceof String) {
                longitude = (String) obj;
            }
        }
        if (soapObject.hasProperty("name")) {
            Object obj = soapObject.getProperty("name");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                name = j.toString();
            } else if (obj != null && obj instanceof String) {
                name = (String) obj;
            }
        }
        if (soapObject.hasProperty("neutralIcon")) {
            Object obj = soapObject.getProperty("neutralIcon");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                neutralIcon = j.toString();
            } else if (obj != null && obj instanceof String) {
                neutralIcon = (String) obj;
            }
        }
        if (soapObject.hasProperty("nickName")) {
            Object obj = soapObject.getProperty("nickName");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                nickName = j.toString();
            } else if (obj != null && obj instanceof String) {
                nickName = (String) obj;
            }
        }
        if (soapObject.hasProperty("state")) {
            Object obj = soapObject.getProperty("state");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                state = j.toString();
            } else if (obj != null && obj instanceof String) {
                state = (String) obj;
            }
        }
        if (soapObject.hasProperty("telephone")) {
            Object obj = soapObject.getProperty("telephone");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                telephone = j.toString();
            } else if (obj != null && obj instanceof String) {
                telephone = (String) obj;
            }
        }
        if (soapObject.hasProperty("town")) {
            Object obj = soapObject.getProperty("town");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                town = j.toString();
            } else if (obj != null && obj instanceof String) {
                town = (String) obj;
            }
        }
        if (soapObject.hasProperty("type")) {
            Object obj = soapObject.getProperty("type");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)) {
                SoapPrimitive j = (SoapPrimitive) obj;
                type = j.toString();
            } else if (obj != null && obj instanceof String) {
                type = (String) obj;
            }
        }
    }

    @Override
    public Object getProperty(int arg0) {
        switch (arg0) {
            case 0:
                return address;
            case 1:
                return addressNumber;
            case 2:
                return administrativeArea;
            case 3:
                return areaCode;
            case 4:
                return category;
            case 5:
                return country;
            case 6:
                return email;
            case 7:
                return family;
            case 8:
                return familyCode;
            case 9:
                return fax;
            case 10:
                return id;
            case 11:
                return idSpecified;
            case 12:
                return latitude;
            case 13:
                return longitude;
            case 14:
                return name;
            case 15:
                return neutralIcon;
            case 16:
                return nickName;
            case 17:
                return state;
            case 18:
                return telephone;
            case 19:
                return town;
            case 20:
                return type;
        }
        return null;
    }

    @Override
    public int getPropertyCount() {
        return 21;
    }

    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch (index) {
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "address";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "addressNumber";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "administrativeArea";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "areaCode";
                break;
            case 4:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "category";
                break;
            case 5:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "country";
                break;
            case 6:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "email";
                break;
            case 7:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "family";
                break;
            case 8:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "familyCode";
                break;
            case 9:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "fax";
                break;
            case 10:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "id";
                break;
            case 11:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "idSpecified";
                break;
            case 12:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "latitude";
                break;
            case 13:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "longitude";
                break;
            case 14:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "name";
                break;
            case 15:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "neutralIcon";
                break;
            case 16:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "nickName";
                break;
            case 17:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "state";
                break;
            case 18:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "telephone";
                break;
            case 19:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "town";
                break;
            case 20:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "type";
                break;
        }
    }


    public String getInnerText() {
        return null;
    }


    public void setInnerText(String s) {
    }


    @Override
    public void setProperty(int arg0, Object arg1) {
    }

}
